services:
  petstore:
    image: api:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:

      - ./:/usr/workspace
#    command: /bin/sh -c "python -m pytest -sv -o log_cli=true -m='$SUITE' --alluredir=report --ignore=gh-pages-dir"
    command: python -m pytest -v --timeout=300 --alluredir=report --ignore=gh-pages-dir

    shm_size: 2gb
#    tty: true

#  report:
#    image: api:v1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/usr/workspace
#    command: /bin/sh -c "allure generate /usr/workspace/report --clean -o /usr/workspace/allure-report"
#    working_dir: /usr/workspace