name: API Tests

on:
  workflow_dispatch:


jobs:
  api-tests:
    runs-on: ubuntu-latest
    env:
      SUITE: ""

    steps:
      - uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-dir
          persist-credentials: false

      - name: Run API Tests
        run: docker compose up petstore

      - name: Fix permissions
        run: sudo chown -R $USER:$USER .

      - name: Copy Allure history
        if: always()
        run: |
          mkdir -p report/history
          if [ -d "gh-pages-dir/history" ]; then
            cp -R gh-pages-dir/history/* report/history/
          fi

      - name: Generate Allure-report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: report
          allure_history: allure-history
          keep_reports: 20

#        run: docker compose up report

#      - name: Fix permissions after report
#        run: sudo chown -R $USER:$USER .
#
#      - name: List files (Debug)
#        run: ls -la

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
#          clean: false
