name: API Tests

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout gh-pages (for history)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages-dir



      - name: Run API Tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: docker compose up petstore

      - name: Fix permissions
        if: always()
        run: sudo chown -R $USER:$USER .

      - name: Copy Allure history
        if: always()
        run: |
          mkdir -p report/history
          if [ -d "gh-pages-dir/history" ]; then
            cp -R gh-pages-dir/history/* report/history/
          fi

      - name: Generate Allure-report
        # Контейнер возьмет данные из report/ и создаст allure-report/
        run: docker compose up report

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: false


