name: API Tests

on:
  workflow_dispatch:


jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout gh-pages (for history)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages-dir # Чтобы не путаться, сменим имя

      - name: Run API Tests
        # Запускаем petstore. Он создаст папку report/ (как прописано в compose)
        run: docker compose up petstore

      - name: Copy Allure history
        # Копируем историю из gh-pages в папку report (которую создал контейнер)
        run: |
          mkdir -p report/history
          if [ -d "gh-pages-dir/history" ]; then
            cp -R gh-pages-dir/history/* report/history/
          fi

      - name: Generate Allure-report
        # Контейнер возьмет данные из report/ и создаст allure-report/
        run: docker compose up report

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report # Тут всё верно
          clean: false


